motor1:
  kp : 750.0
  kd : 4.75
  ff : 0.0
  max_vel : 0.025
  offset : -5.84
motor2:
  kp : 750.0
  kd : 4.75
  ff : 0.0
  max_vel : 0.025
  offset : -3.58
motor3:
  kp : 0.0
  kd : 4.75
  ff : 0.0
  max_vel : 0.025
  offset : 0.0
 motor4:
  kp : 750.0
  kd : 4.75
  ff : 0.0
  max_vel : 0.025
  offset : -3.58
motor5:
  kp : 750.0
  kd : 4.75
  ff : 0.0
  max_vel : 0.025
  offset : -5.84
motor6:
  kp : 0.0
  kd : 4.75
  ff : 0.0
  max_vel : 0.025
  offset : 0.0
motor7:
  kp : 750.0
  kd : 4.75
  ff : 0.0
  max_vel : 0.025
  offset : -5.539